#ifndef ERRMSGS_HPP
# define ERRMSGS_HPP



#define ERR_NOSUCHCHANNEL       403
#define ERR_CANNOTSENDTOCHAN    404
#define ERR_WASNOSUCHNICK       406
#define ERR_NONICKNAMEGIVEN     431
#define ERR_NEEDMOREPARAMS      461
#define ERR_NICKNAMEINUSE       433
#define ERR_ALREADYREGISTERED   462
#define ERR_PASSWDMISMATCH      464

#endif